class WSMEnum:
    DOC_TF_LIST = 0
    DOCLIST = 1
    TFLIST = 2
    AUTHOR = 10
    TITLE = 11
    BOOKTITLE = 12
    YEAR = 13
    PAGE = 14
    VOLUMN = 15
    JOURNAL = 16
    ALLTYPES = 20
    TERM_INSERT_SUCCESS = 3
    TERM_INSERT_FAIL = 4
    TERM_NOT_ENOUGTH = 5
